version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: flowdb
      POSTGRES_USER: flow
      POSTGRES_PASSWORD: flow123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flowdb
      SPRING_DATASOURCE_USERNAME: flow
      SPRING_DATASOURCE_PASSWORD: flow123
    ports:
      - "8080:8080"

volumes:
  pgdata:
